resources:
- ../../base
namespace: main-versions
namePrefix: main-
images:
- name: versions
  newName: ghcr.io/shadinmd/versions
  newTag: main-f61dd96
replicas:
- count: 3
  name: versions
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
