resources:
  - ../../base
namespace: dev-versions
namePrefix: dev-
images:
  - name: versions
    newTag: dev
replicas:
  - name: versions
    count: 1
patches:
  - target:
      kind: Ingress
      name: versions
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dev-versions.nodecluster.online
