resources:
- ../../base
namespace: dev-versions
namePrefix: dev-
images:
- name: versions
  newName: ghcr.io/shadinmd/versions
  newTag: dev-db3d291
replicas:
- count: 1
  name: versions
patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: dev-versions.nodecluster.online
  target:
    kind: Ingress
    name: versions
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
